# Generated by Django 5.0.4 on 2024-04-15 22:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150)),
                ('author_name', models.CharField(max_length=200)),
                ('requested_or_not', models.BooleanField(default=False)),
                ('booked_or_not', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_add_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_logout.books')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
