# Generated by Django 5.0.4 on 2024-04-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbooks',
            name='user_id',
        ),
    ]
