# Generated by Django 5.0.4 on 2024-04-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0003_books_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='user_id',
            new_name='requested_user_id',
        ),
    ]
