# Generated by Django 5.0.4 on 2024-04-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0006_rename_book_name_books_euipment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='availabilty',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
