# Generated by Django 5.0.4 on 2024-04-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0007_alter_books_availabilty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author_name',
        ),
    ]
