# Generated by Django 5.0.4 on 2024-04-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0008_remove_books_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='return_days',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
