# Generated by Django 5.0.4 on 2024-04-17 00:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0009_books_return_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_logout.books')),
            ],
        ),
        migrations.DeleteModel(
            name='IssuedBooks',
        ),
    ]
