# Generated by Django 5.0.4 on 2024-04-18 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0012_historicalbookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbookings',
            name='booked_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login_logout.bookedequipments'),
        ),
    ]
