# Generated by Django 5.0.4 on 2024-04-18 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0014_alter_historicalbookings_booked_equipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedequipments',
            options={'verbose_name': 'BookedEquipment'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book'},
        ),
        migrations.AlterModelOptions(
            name='historicalbookings',
            options={'verbose_name': 'HistoricalBooking'},
        ),
        migrations.AlterModelOptions(
            name='pendingusers',
            options={'verbose_name': 'PendingUser'},
        ),
        migrations.AlterField(
            model_name='historicalbookings',
            name='booked_equipment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_logout.books'),
        ),
    ]
