# Generated by Django 5.0.1 on 2024-04-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0015_alter_bookedequipments_options_alter_books_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingusers',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
